# Copyright 2022 OmniSafe Team. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

defaults:
  # --------------------------------------Basic Configurations----------------------------------- #
  ## -----------------------------Basic configurations for base class PG------------------------ ##
  # The random seed
  seed: 0
  # The environment wrapper type
  wrapper_type: ModelBasedEnvWrapper
  # Number of training time step
  max_real_time_steps: 1000000
  # Number of timestep in an episode
  max_ep_len: 1000
  # CUDA or CPU device
  device: "cuda:0"
  # Number of repeated action
  action_repeat: 5
  # The Address for saving training process data
  data_dir: "./runs"
  # Reward discounted factor
  gamma: 0.99
  # Cost discounted factor
  cost_gamma: 1
  # Noise add to action for exploration
  exploration_noise: 0.0
  # Size of Off-policy Buffer
  replay_size: 1000000
  # Batch size of Off-policy Buffer
  batch_size: 256
  # log information every `log_freq` timesteps
  log_freq: 20000
  # update dynamics every `update_dynamics_freq` timesteps
  update_dynamics_freq: 1000

  ## ----------------------------Basic configurations for dynamics model-------------------- ##
  dynamics_cfgs:
    # Number of network for ensemble model
    network_size: 5
    # output size for ensemble model
    elite_size: 5
    # Size of hidden layers
    hidden_size: 200
    # Whether use decay loss
    use_decay: True

  ## ----------------------------Basic configurations for MPC controller-------------------- ##
  mpc_config:
    # Planning horizon
    horizon: 8
    # Sample population
    popsize: 500
    # Repeat sample population 'particles' times
    particles: 20
    # Number of planning iteration
    max_iters: 5
    # Update coefficicent for new mean and var
    alpha: 0.1
    # Mixed actor sample to gaussian sample
    mixture_coefficient: 0.0
    # Number of elite action trajectories
    minimal_elites: 50
    # Var threshold to stop planning iteration
    epsilon: 0.001
    # Clip observation to [-obs_clip, obs_clip]
    obs_clip: 1000

  ## ----------------------------------Configuration For Lagrangian multiplier---------------------- ##
  lagrange_cfgs:
    # Tolerance of constraint violation
    cost_limit: 0
    # Initial value of lagrangian multiplier
    lagrangian_multiplier_init: 1.0
    # Learning rate of lagrangian multiplier
    lambda_lr: 0.1
    # Type of lagrangian optimizer
    lambda_optimizer: "Adam"
    # scaling factor of cost limit
    beta: 1
